interface StoryData {
  id: number;
  name: string | null;
  text: string;
  image: string | null;
  item?: string | null;
  effect?: string | null;
}

const storyData: StoryData[] = [
  {
    id: 1,
    name: null,
    text: "",
    image: null,
    effect: null,
  },
  {
    id: 2,
    name: "수상한 남자",
    text: "'시간이 늦어서 죄송합니다. 담보로 맡을 물건 있어서요. 전당 거래를 할려고 합니다'",
    image: "frontmen3",
    effect: null,
  },
  {
    id: 3,
    name: "수상한 남자",
    text: "(낡은 가방에서 무언가를 꺼내면서) '이겁니다.'",
    image: "frontmen3",
    effect: null,
  },
  {
    id: 4,
    name: "수상한 남자",
    text: "(눈웃을 지으며) '5개의 보석이 박혀 있는 건틀렛, 단순히 보기 좋은 물건은 아닙니다.'",
    image: "frontmen3",
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 5,
    name: "수상한 남자",
    text: "'얼마까지 대출 할 수 있죠?'",
    image: "frontmen3",
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 6,
    name: "수상한 남자",
    text: "'...알겠습니다.'",
    image: "frontmen3",
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 7,
    name: "수상한 남자",
    text: "(싸인)",
    image: "frontmen3",
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 8,
    name: "수상한 남자",
    text: "...네 금전이 필요해서요. 저에게는 소중하지만 어쩔 수 없죠. 곧 되돌려 받으로 올 겁니다.",
    image: "frontmen3",
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 9,
    name: "수상한 남자",
    text: "(갑자기 눈웃음이 사라지며 진지한 눈빛으로 나를 바라본다)",
    image: "frontmen3",
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 10,
    name: "수상한 남자",
    text: "'...예민한 물건이니 착용하는 일이 없었으면 합니다.'",
    image: "frontmen3",
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 11,
    name: null,
    text: "",
    image: null,
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 12,
    name: null,
    text: "",
    image: null,
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 13,
    name: null,
    text: "",
    image: null,
    item: "gauntletItem",
    effect: null,
  },
  {
    id: 14,
    name: null,
    text: "",
    image: null,
    item: null,
    effect: "흰화면",
  },
  {
    id: 15,
    name: null,
    text: "",
    image: null,
    item: null,
    effect: null,
  },
  {
    id: 16,
    name: null,
    text: "",
    image: null,
    item: null,
    effect: null,
  },
  {
    id: 17,
    name: "소녀",
    text: "!!",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 18,
    name: "소녀",
    text: "아니..그대는 지구인 아닌가",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 19,
    name: "소녀",
    text: "내 이름은 엘리스. 마법사라네!",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 20,
    name: "엘리스",
    text: "그렇소 몇 년에 한번씩 차원의 마석을 사용해서 극비리로 지구와 왕래를 한다네!.",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 21,
    name: "엘리스",
    text: "어떻게 된거죠? 우리가 파견한 마법사가 다시 오기로 했는데..어째서 당신이..",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 22,
    name: "엘리스",
    text: "그 귀중한 물건을 당신 한테 맡겼다고..?",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 23,
    name: "엘리스",
    text: "하...정말 골치 아프게 되었네..안그래도 몇 년전에 차원의 문이 열려 지구의 다양한 물건들이 이 나라에에 뿔뿔이 흩어졌는데데...",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 24,
    name: "엘리스",
    text: "네..하지만 그런 물건들이 이 세계에 시장 경제를 망치고 있습니다. ",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 25,
    name: "엘리스",
    text: "그래서 지구에 마법사를 파견하여 물건의 실태와 사용법을 익혀 이 나라에 시장 경제를 바로 잡을려고 했습니다..하지만...",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 26,
    name: "엘리스",
    text: "조금 힘들것 같습니다..대규모로 들어온 물건들을 기술적으로 다시 돌려 보내는 방법이 없습니다.",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 27,
    name: "엘리스",
    text: "그게...지구로 다시 돌려 보낼 수 있지만...시간이 많이 걸린다네. 한번 차원을 넘나들면 마석들이 이 세상에 뿔뿔이 흐터지게 됩니다. ",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 28,
    name: "엘리스",
    text: "우리는 이 마석들을 회수해서 다시 차원으로 넘나 들 수 있는 거라네.",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 29,
    name: "엘리스",
    text: "지구인 나랑 거래 하지..우리 마법사들이 차원의 마석을 찾기 위해 원정을 떠날테니 이 세계에 전당포를 운영해서 경제 시장을 바로 잡아 줄 수 있겠나나?",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 30,
    name: "엘리스",
    text: "네 사실은 이 세계에는 전당포라는 개념이 없습니다. 저는 우연히 지구의 지식을 조금 알게 되어 말씀드릴 수 있지만...",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 31,
    name: "엘리스",
    text: "네 맞습니다. 부탁드리겠습니다.",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 32,
    name: "엘리스",
    text: "감사합니다. 여기 가게를 드리도록 하겠습니다. 제가 가지고 있는 자본과 미스텔란의 지식이 적혀 있는 책들을 드리겠습니다.",
    image: "master",
    item: null,
    effect: null,
  },
  {
    id: 33,
    name: null,
    text: "",
    image: null,
    item: null,
    effect: null,
  },
];

export default storyData;
